parallel-jobs = 1
patches-version = "latest"
# cli-version = "dev"
enable-magisk-update = true

[instagram-revanced]
enabled = true
app-name = "instagram"
rv-brand = "revanced"
arch = "arm64-v8a"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
included-patches = "'Hide ads' 'Anonymous story viewing' 'Enable developer menu' 'Disable analytics' 'Open links externally' 'Remove build expired popup' 'Sanitize sharing links'"
exclusive-patches = true
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
dpi = "160-480dpi 320dpi 480dpi 480-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram"
