parallel-jobs = 1
patches-version = "dev"
# cli-version = "dev"
enable-module-update = false

[youtube-morphe-exp]
enabled = true
app-name = "youtube"
rv-brand = "morphe-exp"
build-mode = "both"
arch = "both"
version = "exp"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"
apkpure-dlurl = "https://apkpure.com/youtube-app/com.google.android.youtube"
apkcombo-dlurl = "https://apkcombo.com/youtube/com.google.android.youtube"
