[NiagaraLauncher-Entree3k]
enabled = true
pkg-name = "bitpit.launcher"
app-name = "Niagara Launcher"
patch-folder = "niagara"
build-mode = "both"
patches-source = "Entree3k/Morning-Entree-Patches"
brand = "Entree3k"
apkmirror-dlurl = "https://www.apkmirror.com/apk/mellowdrop-studio/niagara-launcher-%f0%9f%94%b9-fresh-clean"
uptodown-dlurl = "https://niagara-launcher.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/niagara-launcher-%E2%80%A7-fresh-clean/bitpit.launcher"
apkcombo-dlurl = "https://apkcombo.com/niagara-launcher/bitpit.launcher"