patches-source = "Aunali321/ReVancedExperiments"
cli-source = "ReVanced/revanced-cli"
brand = "Aunali321"

[Instagram-Aunali321]
enabled = true
pkg-name = "com.instagram.android"
app-name = "Instagram"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
