cli-source = "7723mod/NPatch"

[Discord-revenge]
enabled = true
patches-source = "revenge-mod/revenge-xposed"
patches-version = "both"
brand = "revenge"
pkg-name = "com.discord"
app-name = "Discord"
patcher-args = "-l 0"
apkmirror-dlurl = "https://www.apkmirror.com/apk/discord/discord-chat-for-gamers"
apkcombo-dlurl = "https://apkcombo.com/discord/com.discord"

[Discord-rain]
enabled = true
patches-source = "raincord/rainXposed"
patches-source-host = "codeberg"
patches-version = "stable"
brand = "rain"
pkg-name = "com.discord"
app-name = "Discord"
patcher-args = "-l 0"
apkmirror-dlurl = "https://www.apkmirror.com/apk/discord/discord-chat-for-gamers"
apkcombo-dlurl = "https://apkcombo.com/discord/com.discord"
