patches-source = "ajstrick81/morphe-androidtv-patches"
patches-version = "stable"
brand = "ajstrick81"
variant = "Android TV"
arch = "all"

[disneyplus-ajstrick81-androidtv]
enabled = true 
pkg-name = "com.disney.disneyplus"
app-name = "Disney+"
apkmirror-dlurl = "https://www.apkmirror.com/apk/disney/disney-android-tv"
apkpure-dlurl = "https://apkpure.com/disneyplus-app/com.disney.disneyplus"
apkcombo-dlurl = "https://apkcombo.com/disney-plus/com.disney.disneyplus"

[prime-video-ajstrick81-androidtv]
enabled = true 
pkg-name = "com.amazon.amazonvideo.livingroom"
app-name = "Prime Video"
arch = "arm-v7a"
dpi = "nodpi anydpi 320dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/prime-video-android-tv-android-tv"

[prime-video-ajstrick81-androidtv-clone]
enabled = true 
pkg-name = "com.amazon.amazonvideo.livingroom"
app-name = "Prime Video"
sub-variant = "Clone"
arch = "arm-v7a"
included-patches = "'Clone Prime Video'"
dpi = "nodpi anydpi 320dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/prime-video-android-tv-android-tv"

[hbomax-ajstrick81-androidtv]
enabled = true 
pkg-name = "com.wbd.hbomax"
app-name = "HBO Max"
apkmirror-dlurl = "https://www.apkmirror.com/apk/warnermedia-direct-llc/hbo-max-stream-movies-tv-android-tv"

[peacock-ajstrick81-androidtv]
enabled = true 
pkg-name = "com.peacocktv.peacockandroid"
app-name = "Peacock"
apkmirror-dlurl = "https://www.apkmirror.com/apk/peacock-tv-llc/peacock-tv-android-tv"
apkcombo-dlurl = "https://apkcombo.com/peacock-tv/com.peacocktv.peacockandroid"

[tubi-ajstrick81-androidtv]
enabled = true 
pkg-name = "com.tubitv"
app-name = "Tubi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tubi-tv/tubi-free-movies-live-tv-android-tv"

[vix-ajstrick81-androidtv]
enabled = true 
pkg-name = "com.univision.prendetv"
app-name = "ViX"
apkmirror-dlurl = "https://www.apkmirror.com/apk/univision-communications-inc/vix-cine-y-tv-en-espanol-android-tv"
apkpure-dlurl = "https://apkpure.com/vix-tv-deportes-y-noticias/com.univision.prendetv"
apkcombo-dlurl = "https://apkcombo.com/vix/com.univision.prendetv/"

[plutotv-ajstrick81-androidtv]
enabled = true 
pkg-name = "tv.pluto.android"
app-name = "PlutoTV"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pluto-inc/pluto-tv-android-tv"
uptodown-dlurl = "https://pluto-tv.en.uptodown.com/android"

[netflix-ajstrick81-androidtv]
enabled = true 
pkg-name = "com.netflix.ninja"
app-name = "Netflix"
arch = "arm-v7a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/netflix-inc/netflix-android-tv"
uptodown-dlurl = "https://netflix-inc-netflix.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/netflix-android-tv-app/com.netflix.ninja"
apkcombo-dlurl = "https://apkcombo.com/netflix-tv/com.netflix.ninja"

[twitch-ajstrick81-androidtv]
enabled = true 
pkg-name = "tv.twitch.android.app"
app-name = "Twitch"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch-android-tv/"
apkpure-dlurl = "https://apkpure.com/twitch-livestream-multiplayer-games-esports-app/tv.twitch.android.app"
apkcombo-dlurl = "https://apkcombo.com/twitch/tv.twitch.android.app"
