patches-source = "bufferk/morphe-patches"
brand = "Morphe"

[truecaller-morphe-alt]
enabled = true
pkg-name = "com.truecaller"
app-name = "truecaller"
sub-variant = "alt"
build-mode = "both"
arch = "both"
uptodown-dlurl = "https://truecaller.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/true-software-scandinavia-ab/truecaller-caller-id-block"
archive-dlurl = "https://archive.org/download/geologically/apks/com.truecaller"

[medium-morphe]
enabled = true
pkg-name = "com.medium.reader"
app-name = "medium"
build-mode = "apk"
arch = "both"
uptodown-dlurl = "https://medium.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/a-medium-corporation/medium"
