

[google-photos-morphe]
enabled = true
pkg-name = "com.google.android.apps.photos"
app-name = "Google Photos"
brand = "Morphe"
build-mode = "both"
arch = "both"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-desktop"
# uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.photos"

[instagram-morphe]
enabled = true
pkg-name = "com.instagram.android"
app-name = "Instagram"
brand = "Morphe"
build-mode = "apk"
arch = "both"
patches-source = "brosssh/morphe-patches"
# patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
archive-dlurl = "https://archive.org/download/geologically/apks/com.instagram.android"

[tiktok-morphe]
enabled = true
pkg-name = "com.zhiliaoapp.musically"
app-name = "TikTok"
brand = "Morphe"
build-mode = "apk"
arch = "both"
patches-source = "icysymmetra/tiktok-patches-for-morphe"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
archive-dlurl = "https://archive.org/download/geologically/apks/com.zhiliaoapp.musically"

[reddit-adobo]
enabled = true
pkg-name = "com.reddit.frontpage"
app-name = "Reddit"
brand = "Adobo"
build-mode = "apk"
arch = "both"
patches-source = "jkennethcarino/adobo"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"
