patches-source = "jkennethcarino/adobo"

[imdb-jkennethcarino]
enabled = true
pkg-name = "com.imdb.mobile"
app-name = "IMDb"
brand = "jkennethcarino"
build-mode = "apk"
arch = "all"
uptodown-dlurl = "https://imdb-cine-tv.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/imdb/imdb-imdb"
