[twitter-piko]
enabled = true 
pkg-name = "com.twitter.android"
app-name = "Twitter"
brand = "Piko"
build-mode = "both"
arch = "both"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
apkpure-dlurl = "https://apkpure.com/x-formerly-twitter/com.twitter.android"

[twitter-piko-materialu]
enabled = true
pkg-name = "com.twitter.android"
app-name = "Twitter"
brand = "Piko"
variant = "MaterialYou"
build-mode = "both"
arch = "both"
patches-source = "crimera/piko"
included-patches = "'Bring back twitter' 'Dynamic color'"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
apkpure-dlurl = "https://apkpure.com/x-formerly-twitter/com.twitter.android"

[instagram-piko]
enabled = true
pkg-name = "com.instagram.android"
app-name = "Instagram"
brand = "Piko"
build-mode = "both"
arch = "arm64-v8a"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"

[instagram-piko-clone]
enabled = true
pkg-name = "com.instagram.android"
app-name = "Instagram"
brand = "Piko"
sub-variant = "clone"
included-patches = "'Change package name'"
build-mode = "both"
arch = "arm64-v8a"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
