[Photomath-DeVanced]
enabled = true
pkg-name = "com.microblink.photomath"
app-name = "Photomath"
patches-source = "RookieEnough/De-Vanced"
brand = "DeVanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photomath"
uptodown-dlurl = "https://photomath.en.uptodown.com/android"

[Telegram-rushiranpise-GooglePlay]
enabled = true
pkg-name = "org.telegram.messenger"
app-name = "Telegram"
variant = "Google Play"
patches-source = "rushiranpise/morphe-patches"
brand = "rushiranpise"
uptodown-dlurl = "https://telegram-google-play-version.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/telegram-fz-llc/telegram"

[Facebook-andrewliang25]
enabled = true
pkg-name = "com.facebook.katana"
app-name = "Facebook"
patches-source = "andrewliang25/morphe-patches"
brand = "andrewliang25"
included-patches = "'[General] AMOLED black theme' '[Reels] Download any reel'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/facebook-app/com.facebook.katana"
apkcombo-dlurl = "https://apkcombo.com/facebook/com.facebook.katana"
# roundtrip-test
