[AtvTools-hxreborn]
enabled = true
pkg-name = "dev.vodik7.atvtools"
app-name = "atvTools"
patches-source = "hxreborn/morphe-patches"
brand = "hxreborn"
apkpure-dlurl = "https://apkpure.com/atvtools/dev.vodik7.atvtools"
apkcombo-dlurl = "https://apkcombo.com/atvtools/dev.vodik7.atvtools"

[TikTok-hushfeed]
enabled = true
pkg-name = "com.zhiliaoapp.musically"
app-name = "TikTok"
patches-source = "SysAdminDoc/hushfeed"
brand = "hushfeed"
inclusive-patches = true
excluded-patches = "'Remove unused language packs'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/tiktok-app/com.zhiliaoapp.musically"
apkcombo-dlurl = "https://apkcombo.com/tiktok-videos-shop-live/com.zhiliaoapp.musically"